dependencies:
  flutter:
    sdk: flutter
  http: ^0.14.0
  cached_network_image: ^3.0.0
  shared_preferences: ^2.0.0
  flutter_staggered_grid_view: ^0.4.0
  zoom_pinch_overlay: ^2.0.0  # For zooming in/out images
  provider: ^6.0.0
